<?xml version="1.0"?>
<!DOCTYPE NEWSPAPER[
	<!ELEMENT NEWSPAPER (ARTICLE+)>
	<!ELEMENT ARTICLE (HEADLINE, BYLINE, LEAD, BODY, NOTES)>
	<!ELEMENT HEADLINE (#PCDATA)>
	<!ELEMENT BYLINE (#PCDATA)>
	<!ELEMENT LEAD (#PCDATA)>
	<!ELEMENT BODY (#PCDATA)>
	<!ELEMENT NOTES (#PCDATA)>

	<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
	<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
	<!ATTLIST ARTICLE DATA CDATA #IMPLIED>
	<!ATTLIST ARTICLE EDITION CDATA #IMPLIED>
 ]>
 <NEWSPAPER>
 	<ARTICLE AUTHOR="TU LING" EDITOR="BIAO" DATA="2014/05/03">
 		<HEADLINE>NODE JS </HEADLINE>
 		<BYLINE>LEANR NODE JS </BYLINE>
 		<LEAD> </LEAD>
 		<BODY>NODE JS IS JAVASCRIPT LANGUAGE </BODY>
 		<NOTES>BY TULING</NOTES>
 	</ARTICLE>
 </NEWSPAPER>

