<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE poem[
	<!ELEMENT poem (author+, title, content)>
	<!ELEMENT author (#PCDATA)>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT content (#PCDATA)>
]>
<poem>
 <author>王维</author>
 <author>李白</author>
 <title>鹿柴</title>
 <content>空山不见人，但闻人语声。
 返景入深林，复照青苔上。
 </content>
</poem>